# .ruff.toml

line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I"]  # E: PEP8(pycodestyle), F: Pyflakes, I: import 정렬(isort)
ignore = ["E501"]         # 줄 길이 제한 무시 (선택)

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"