services:
  db_test:
    image: postgres:15
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "${TEST_DB_PORT:-55432}:5432"
    volumes:
      - test_postgre_data:/var/lib/postgresql/data
    env_file:
      - .env.test

volumes:
  test_postgre_data: