# Generated by Django 5.2.4 on 2025-07-16 08:17

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models

import apps.artworks.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_created",
                    models.IntegerField(
                        help_text="작품이 제작된 년도",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(
                                limit_value=apps.artworks.models.get_current_year,
                                message="제작 연도는 현재 연도보다 클 수 없습니다.",
                            ),
                        ],
                        verbose_name="제작년도",
                    ),
                ),
                (
                    "price_krw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="한국 원화 기준 가격",
                        max_digits=12,
                        null=True,
                        verbose_name="가격(원화)",
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="미국 달러 기준 가격",
                        max_digits=12,
                        null=True,
                        verbose_name="가격(달러)",
                    ),
                ),
                (
                    "materials",
                    models.TextField(help_text="예: 캔버스에 아크릴, 브론즈 등", verbose_name="재료"),
                ),
                (
                    "width",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="가로(cm)",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="세로(cm)",
                    ),
                ),
                (
                    "depth",
                    models.FloatField(
                        blank=True,
                        help_text="조각품 등에 적용",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="깊이(cm)",
                    ),
                ),
                (
                    "dimension_unit",
                    models.CharField(
                        choices=[("cm", "Centimeter"), ("inch", "Inch")],
                        default="cm",
                        max_length=10,
                        verbose_name="크기 단위",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("painting", "회화"),
                            ("oriental_painting", "동양화"),
                            ("sculpture", "조소"),
                            ("printmaking", "판화"),
                            ("wood_craft", "목조"),
                            ("ceramics", "도예"),
                            ("metal_craft", "금속조형"),
                            ("photography", "사진"),
                            ("digital", "디지털아트"),
                            ("mixed_media", "혼합매체"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "판매중"),
                            ("sold", "판매완료"),
                            ("reserved", "예약중"),
                            ("not_for_sale", "판매안함"),
                        ],
                        default="not_for_sale",
                        max_length=20,
                        verbose_name="판매 상태",
                    ),
                ),
                (
                    "copyright_agreed",
                    models.BooleanField(
                        default=False,
                        help_text="작품 업로드 시 저작권 관련 동의 여부",
                        verbose_name="저작권 동의",
                    ),
                ),
                (
                    "license_agreed",
                    models.BooleanField(
                        default=False,
                        help_text="플랫폼 이용 라이선스 동의 여부",
                        verbose_name="라이선스 동의",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "like_count",
                    models.PositiveIntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="메인 페이지에 노출될 추천 작품 여부",
                        verbose_name="큐레이터 추천",
                    ),
                ),
                (
                    "featured_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="추천 등록일"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="삭제됨")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="삭제일시"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="artists.artist",
                        verbose_name="작가",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ArtworkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="artworks/%Y/%m/", verbose_name="이미지"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="대표 이미지"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="정렬 순서")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="접근성을 위한 이미지 설명",
                        max_length=200,
                        verbose_name="대체 텍스트",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일시"),
                ),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="artworks.artwork",
                        verbose_name="작품",
                    ),
                ),
            ],
            options={
                "verbose_name": "작품 이미지",
                "verbose_name_plural": "작품 이미지들",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("artwork",),
                        name="unique_primary_image_per_artwork",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArtworkTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "title",
                    models.CharField(db_index=True, help_text="작품명", max_length=150),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="작품에 대한 상세 설명", verbose_name="작품 설명"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation",
                        to="artworks.artwork",
                    ),
                ),
            ],
            options={
                "verbose_name": "artwork Translation",
                "db_table": "artworks_artwork_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
