# Generated by Django 5.2.4 on 2025-08-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="status",
        ),
        migrations.RemoveField(
            model_name="artworkimage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="artworkimage",
            name="is_primary",
        ),
        migrations.AddField(
            model_name="artwork",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "승인대기"), ("approved", "승인"), ("rejected", "거절")],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="승인 상태",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="작품의 대표 이미지",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="artworks.artworkimage",
                verbose_name="대표 이미지",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="display_status",
            field=models.CharField(
                choices=[("public", "공개"), ("hidden", "비공개")],
                db_index=True,
                default="public",
                max_length=20,
                verbose_name="공개 여부",
            ),
        ),
        migrations.AddField(
            model_name="artwork",
            name="sale_status",
            field=models.CharField(
                choices=[
                    ("available", "판매중"),
                    ("sold", "판매완료"),
                    ("reserved", "예약중"),
                    ("not_for_sale", "판매안함"),
                ],
                db_index=True,
                default="not_for_sale",
                max_length=20,
                verbose_name="판매 상태",
            ),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="key",
            field=models.CharField(blank=True, null=True, verbose_name="이미지 키"),
        ),
        migrations.AddField(
            model_name="artworkimage",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="이미지 URL"),
        ),
    ]
