# Generated by Django 5.2.4 on 2025-08-20 13:05

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0002_remove_artwork_status_remove_artworkimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artworktranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="artworks.artwork",
            ),
        ),
    ]
