# Generated by Django 5.2.4 on 2025-08-20 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0003_alter_artworktranslation_master"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="artworkimage",
            name="unique_primary_image_per_artwork",
        ),
    ]
