# Generated by Django 5.2.4 on 2025-08-20 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0003_alter_artworktranslation_master"),
    ]

    operations = [
        migrations.RunSQL(
            # Postgres: 부분 유니크는 인덱스로 구현됨
            sql="DROP INDEX IF EXISTS unique_primary_image_per_artwork;",
            reverse_sql="-- no-op",
        ),
    ]
