# Generated by Django 5.2.4 on 2025-08-20 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0004_remove_artworkimage_unique_primary_image_per_artwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="year_created",
            field=models.IntegerField(
                help_text="작품이 제작된 년도",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(
                        limit_value=2025, message="제작 연도는 현재 연도보다 클 수 없습니다."
                    ),
                ],
                verbose_name="제작년도",
            ),
        ),
    ]
