# Generated by Django 5.2.4 on 2025-08-21 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0005_alter_artwork_year_created"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # DB는 건드리지 않음 (이미 없음/이름 모름 대비)
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="artworkimage",
                    name="unique_primary_image_per_artwork",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="artwork",
            name="depth",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="조각품 등에 적용",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="깊이(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="세로(cm)",
            ),
        ),
        migrations.AlterField(
            model_name="artwork",
            name="width",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(0.1)],
                verbose_name="가로(cm)",
            ),
        ),
    ]
