# Generated by Django 5.2.4 on 2025-07-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
