# Generated by Django 5.2.4 on 2025-08-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approval_status',
        ),
    ]
