# Generated by Django 5.2.4 on 2025-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_user_approval_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image_url",
            field=models.URLField(blank=True, help_text="Image URL for user profile", null=True),
        ),
    ]
