# Generated by Django 5.2.4 on 2025-08-01 13:25

import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='프로필 이미지', null=True, upload_to='artists/profile/')),
                ('artwork_count', models.PositiveIntegerField(default=0, help_text='등록 작품 수')),
                ('follower_count', models.PositiveBigIntegerField(default=0, help_text='팔로워 수')),
                ('is_featured', models.BooleanField(default=False, help_text='추천 작가 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '아티스트',
                'verbose_name_plural': '아티스트들',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ArtistTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('artist_name', models.CharField(db_index=True, help_text='작가명', max_length=150)),
                ('artist_note', models.TextField(blank=True, help_text='작가 소개 및 작품 세계관', verbose_name='작가노트')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='artists.artist')),
            ],
            options={
                'verbose_name': '아티스트 Translation',
                'db_table': 'artists_artist_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['created_at'], name='artists_art_created_2e2ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['follower_count'], name='artists_art_followe_3186f0_idx'),
        ),
        migrations.AddIndex(
            model_name='artist',
            index=models.Index(fields=['is_featured'], name='artists_art_is_feat_c1fafe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='artisttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
