# Generated by Django 5.2.4 on 2025-08-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='artist',
            name='main_image',
            field=models.ImageField(blank=True, help_text='대표작품 이미지', null=True, upload_to='artists/profile/'),
        ),
    ]
