# Generated by Django 5.2.4 on 2025-08-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_profile_image_artist_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
