# Generated by Django 5.2.4 on 2025-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artists", "0003_artist_approval_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="main_image",
        ),
        migrations.AddField(
            model_name="artist",
            name="main_image_url",
            field=models.URLField(
                blank=True, help_text="Image URL for artist main image", null=True
            ),
        ),
    ]
