name: Django CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                ports: ['5432:5432']
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                options: >-
                    --health-cmd "pg_isready -U postgres"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        env:
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
            DEBUG: "False"
            
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r /backend/requirements/development.txt

            - name: Run tests
              run: |
                python manage.py migrate
                pytest -v --ds=
              working-directory: /backend
